"""Add article generation models

Revision ID: 51c2ec7d26bc
Revises: 372c86178397
Create Date: 2026-09-27 13:42:46.068339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '51c2ec7d26bc'
down_revision: Union[str, Sequence[str], None] = '372c86178397'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_sources',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['generated_articles.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'source_id')
    )
    op.create_table('editorial_corrections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('original_draft', sa.Text(), nullable=True),
    sa.Column('corrected_content', sa.Text(), nullable=True),
    sa.Column('correction_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['generated_articles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_index(op.f('ix_editorial_corrections_id'), 'editorial_corrections', ['id'], unique=False)
    op.create_table('news_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('full_content', sa.Text(), nullable=True),
    sa.Column('cleaned_content', sa.Text(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_news_contents_id'), 'news_contents', ['id'], unique=False)
    op.create_table('news_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_news_embeddings_id'), 'news_embeddings', ['id'], unique=False)
    op.alter_column('claims', 'claim_text',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('claims', 'evidence',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('generated_articles', 'content',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('sources', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sources', 'description',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('generated_articles', 'content',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('claims', 'evidence',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('claims', 'claim_text',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_news_embeddings_id'), table_name='news_embeddings')
    op.drop_table('news_embeddings')
    op.drop_index(op.f('ix_news_contents_id'), table_name='news_contents')
    op.drop_table('news_contents')
    op.drop_index(op.f('ix_editorial_corrections_id'), table_name='editorial_corrections')
    op.drop_table('editorial_corrections')
    op.drop_table('article_sources')
    # ### end Alembic commands ###
