<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\Entitlement;
use App\Models\Product;
use App\Support\Present;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\URL;
use Illuminate\Support\Str;

/**
 * "My Library": everything the user is entitled to.
 * Every content access goes through an ownership check:
 *   authenticated? -> owns product? -> entitlement active? -> allow read / temporary download link
 */
class LibraryController extends Controller
{
    public function index(Request $request)
    {
        $items = $request->user()->entitlements()->active()
            ->with(['product.category', 'product.author', 'order'])
            ->when($request->input('type'), fn ($q, $t) => $q->whereHas('product', fn ($p) => $p->where('type', $t)))
            ->orderByDesc('last_accessed_at')->orderByDesc('granted_at')
            ->get()
            ->filter(fn ($e) => $e->product);

        return response()->json(['data' => $items->map(fn ($e) => Present::libraryItem($e))->values()]);
    }

    protected function entitlementFor(Request $request, string $slug): Entitlement
    {
        $product = Product::where('slug', $slug)->firstOrFail();
        $entitlement = $request->user()->entitlements()->active()->where('product_id', $product->id)->first();
        abort_unless($entitlement, 403, 'Kamu belum memiliki akses ke produk ini.');
        $entitlement->setRelation('product', $product);

        return $entitlement;
    }

    /** Full protected content (online reader). */
    public function read(Request $request, string $slug)
    {
        $e = $this->entitlementFor($request, $slug);
        $p = $e->product->load('category', 'author');
        abort_unless($p->canRead(), 422, 'Produk ini tidak tersedia untuk dibaca online.');

        $e->forceFill(['last_accessed_at' => now()])->save();

        return response()->json([
            'product' => Present::productDetail($p, true),
            'content_html' => $p->content_html,
            'sources' => $p->sources ?? [],
            'progress' => (int) $e->progress,
        ]);
    }

    public function progress(Request $request, string $slug)
    {
        $data = $request->validate(['progress' => ['required', 'integer', 'min:0', 'max:100']]);
        $e = $this->entitlementFor($request, $slug);
        $e->forceFill(['progress' => max($e->progress, $data['progress']), 'last_accessed_at' => now()])->save();

        return response()->json(['progress' => $e->progress]);
    }

    /** Returns a short-lived signed URL; the real file location is never exposed. */
    public function downloadLink(Request $request, string $slug)
    {
        $e = $this->entitlementFor($request, $slug);
        abort_unless($e->product->canDownload(), 422, 'Produk ini tidak tersedia untuk diunduh.');

        $url = URL::temporarySignedRoute('library.download', now()->addMinutes(5), ['entitlement' => $e->id]);

        return response()->json(['url' => $url, 'expires_in' => 300]);
    }

    /** Signed route target (no bearer token needed, signature + entitlement checked). */
    public function download(Request $request, Entitlement $entitlement)
    {
        abort_unless($request->hasValidSignature(), 403, 'Link download sudah kedaluwarsa.');
        abort_unless(Entitlement::whereKey($entitlement->id)->active()->exists(), 403);

        $product = $entitlement->product;
        abort_unless($product && $product->canDownload(), 404);

        $entitlement->forceFill(['last_accessed_at' => now()])->save();
        $filename = Str::slug(Str::limit($product->title, 80, '')) ?: 'download';

        // 1) Uploaded private file
        if ($product->file_path && Storage::disk('local')->exists($product->file_path)) {
            $ext = pathinfo($product->file_name ?: $product->file_path, PATHINFO_EXTENSION);

            return Storage::disk('local')->download($product->file_path, $filename.($ext ? '.'.$ext : ''));
        }

        // 2) Article generated by the Article Generator: proxy its PDF export
        if ($product->external_pdf_url) {
            $res = Http::timeout(60)->get($product->external_pdf_url);
            abort_unless($res->successful(), 502, 'PDF belum bisa dibuat. Coba lagi nanti.');

            return response($res->body(), 200, [
                'Content-Type' => 'application/pdf',
                'Content-Disposition' => 'attachment; filename="'.$filename.'.pdf"',
                'Cache-Control' => 'private, no-store',
            ]);
        }

        abort(404);
    }
}
